### ISSUE TITLE
Where is polish language?

### ISSUE THREAD

**Issue by and09** [ashfurrow/mastodon#3]
version

**Comment by ashfurrow** [comment]
It looks like the Polish translation was only recently added to Mastodon, but it is here: https://github.com/tootsuite/mastodon/blob/master/config/locales/pl.yml . Is it not working for you? You should be able to change it under your settings at https://mastodon.technology/settings/preferences

**Comment by and09** [comment]
Where? 
print screen http://bankfotek.pl/thumb/2072298.jpeg
  ![print screen ](http://bankfotek.pl/view/2072298)

**Comment by ashfurrow** [comment]
Gotcha, looks like it hasn't been enabled yet. The next update should fix that, sorry for the wait!

**Comment by and09** [comment]
http://bankfotek.pl/thumb/2072298.jpeg
http://bankfotek.pl/view/2072298

**Comment by ashfurrow** [comment]
Looks like a bug, sorry for the wait! I've tried to fix it but can't figure it out. I'm opening an issue now.

**Comment by ashfurrow** [comment]
I've opened a pull request to fix this: https://github.com/tootsuite/mastodon/pull/2235 I expect it'll be merged soon and included in an upcoming release. Thanks again for your patience.

**Comment by ashfurrow** [comment]
Should be fixed now, I'm going to close. Please re-open if it's not fixed. Thanks again!
