### ISSUE TITLE
Change the fedora emoji to the new logo

### ISSUE THREAD

**Issue by X3MBoy** [ashfurrow/mastodon#65]
### Pitch

The Fedora logo [was updated](https://pagure.io/Fedora-Council/tickets/issue/248#comment-637341) and some instances already changed [the emoji](https://mastodon.technology/web/statuses/106566383106108675)

### Motivation

I think is better to keep up-to-date to the changes on graphical icons and all community will benefit from having the new logo instead of the outdated one.

**Comment by ashfurrow** [comment]
Hi, thanks for opening a GitHub issue. This is a great way to request changes like this 👍 I've updated the emoji and it should be reflected the next time you refresh your browser. The cache on the server side is cleared, but client side caches might keep the old emoji for a bit. Thanks again!
